#pragma once
#include "common.hpp"

enum class keycode : int
{
    unknown,
    none,

    backspace = 8,
    tab = 9,
    enter = 13,
    shift = 16,
    ctrl = 17,
    left_ctrl = 162,
    right_ctrl = 163,
    alt = 18,
    left_alt = 164,
    right_alt = 165,
    pause = 19,
    caps_lock = 20,
    escape = 27,
    space = 32,
    page_up = 33,
    page_down = 34,
    end = 35,
    home = 36,
    left = 37,
    up = 38,
    right = 39,
    down = 40,
    print_screen = 44,
    insert = 45,
    del = 46,

    key_0 = 48,
    key_1 = 49,
    key_2 = 50,
    key_3 = 51,
    key_4 = 52,
    key_5 = 53,
    key_6 = 54,
    key_7 = 55,
    key_8 = 56,
    key_9 = 57,

    key_a = 65,
    key_b = 66,
    key_c = 67,
    key_d = 68,
    key_e = 69,
    key_f = 70,
    key_g = 71,
    key_h = 72,
    key_i = 73,
    key_j = 74,
    key_k = 75,
    key_l = 76,
    key_m = 77,
    key_n = 78,
    key_o = 79,
    key_p = 80,
    key_q = 81,
    key_r = 82,
    key_s = 83,
    key_t = 84,
    key_u = 85,
    key_v = 86,
    key_w = 87,
    key_x = 88,
    key_y = 89,
    key_z = 90,

    left_super = 91,
    right_super = 92,
    select = 93,

    numpad_0 = 96,
    numpad_1 = 97,
    numpad_2 = 98,
    numpad_3 = 99,
    numpad_4 = 100,
    numpad_5 = 101,
    numpad_6 = 102,
    numpad_7 = 103,
    numpad_8 = 104,
    numpad_9 = 105,
    numpad_multiply = 106,
    numpad_add = 107,
    numpad_subtract = 109,
    numpad_decimal = 110,
    numpad_divide = 111,
    numpad_enter = 13,

    mouse = 256,
    mouse_wheel_up = 256,
    mouse_wheel_down,
    mouse_1,
    mouse_2,
    mouse_3,
    mouse_4,
    mouse_5,
};

struct key final
{
    constexpr key(const keycode& code, const std::string_view name) noexcept
        : code(code), name(name)
    {
    }

    keycode code;
    std::string_view name;
};

constexpr auto key_map = std::to_array<key>({
    {keycode::unknown, "Unknown"},
    {keycode::none, "None"},
    {keycode::backspace, "Backspace"},
    {keycode::tab, "Tab"},
    {keycode::enter, "Enter"},
    {keycode::shift, "Shift"},
    {keycode::ctrl, "Ctrl"},
    {keycode::left_ctrl, "Left Ctrl"},
    {keycode::right_ctrl, "Right Ctrl"},
    {keycode::alt, "Alt"},
    {keycode::left_alt, "Left Alt"},
    {keycode::right_alt, "Right Alt"},
    {keycode::pause, "Pause"},
    {keycode::caps_lock, "Caps Lock"},
    {keycode::escape, "Escape"},
    {keycode::space, "Space"},
    {keycode::page_up, "Page Up"},
    {keycode::page_down, "Page Down"},
    {keycode::end, "End"},
    {keycode::home, "Home"},
    {keycode::left, "Left"},
    {keycode::up, "Up"},
    {keycode::right, "Right"},
    {keycode::down, "Down"},
    {keycode::print_screen, "Print Screen"},
    {keycode::insert, "Insert"},
    {keycode::del, "Delete"},
    {keycode::key_0, "0"},
    {keycode::key_1, "1"},
    {keycode::key_2, "2"},
    {keycode::key_3, "3"},
    {keycode::key_4, "4"},
    {keycode::key_5, "5"},
    {keycode::key_6, "6"},
    {keycode::key_7, "7"},
    {keycode::key_8, "8"},
    {keycode::key_9, "9"},
    {keycode::key_a, "A"},
    {keycode::key_b, "B"},
    {keycode::key_c, "C"},
    {keycode::key_d, "D"},
    {keycode::key_e, "E"},
    {keycode::key_f, "F"},
    {keycode::key_g, "G"},
    {keycode::key_h, "H"},
    {keycode::key_i, "I"},
    {keycode::key_j, "J"},
    {keycode::key_k, "K"},
    {keycode::key_l, "L"},
    {keycode::key_m, "M"},
    {keycode::key_n, "N"},
    {keycode::key_o, "O"},
    {keycode::key_p, "P"},
    {keycode::key_q, "Q"},
    {keycode::key_r, "R"},
    {keycode::key_s, "S"},
    {keycode::key_t, "T"},
    {keycode::key_u, "U"},
    {keycode::key_v, "V"},
    {keycode::key_w, "W"},
    {keycode::key_x, "X"},
    {keycode::key_y, "Y"},
    {keycode::key_z, "Z"},
    {keycode::left_super, "Left Super"},
    {keycode::right_super, "Right Super"},
    {keycode::select, "Select"},
    {keycode::numpad_0, "Numpad 0"},
    {keycode::numpad_1, "Numpad 1"},
    {keycode::numpad_2, "Numpad 2"},
    {keycode::numpad_3, "Numpad 3"},
    {keycode::numpad_4, "Numpad 4"},
    {keycode::numpad_5, "Numpad 5"},
    {keycode::numpad_6, "Numpad 6"},
    {keycode::numpad_7, "Numpad 7"},
    {keycode::numpad_8, "Numpad 8"},
    {keycode::numpad_9, "Numpad 9"},
    {keycode::numpad_multiply, "Numpad Multiply"},
    {keycode::numpad_add, "Numpad Add"},
    {keycode::numpad_subtract, "Numpad Subtract"},
    {keycode::numpad_decimal, "Numpad Decimal"},
    {keycode::numpad_divide, "Numpad Divide"},
    {keycode::numpad_enter, "Numpad Enter"},
    {keycode::mouse_wheel_up, "Mouse Wheel Up"},
    {keycode::mouse_wheel_down, "Mouse Wheel Down"},
    {keycode::mouse_1, "Mouse 1"},
    {keycode::mouse_2, "Mouse 2"},
    {keycode::mouse_3, "Mouse 3"},
    {keycode::mouse_4, "Mouse 4"},
    {keycode::mouse_5, "Mouse 5"},
});